### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by aramgev** [regulaforensics/cordova-plugin-documentreader-mrz#2]
Applciations crashes when I call:

 ```
DocumentReader.initReader(
    fileResult,
    onDocReaderReady,
    function (error) {
          alert(error);
    }
);
```

I build application with phonegap build cloud

**Comment by vyakimchik** [comment]
Hello. This repository is no longer supported. Please, use this one: https://github.com/regulaforensics/DocumentReader-Cordova-Plugin.
The documentation on Cordova SDK can be found here: https://docs.regulaforensics.com/cordova.

**Comment by aramgev** [comment]
Hello. Yes I saw this, but the problem is that new repo is not cordova/phonegap plugin it is cordova application. So I think I can not use your new repo with phonegap build cloud.

**Comment by vyakimchik** [comment]
We've created the PhoneGap demo project which can be found here: https://github.com/regulaforensics/DocumentReader-PhoneGap-Plugin. Please, try it out!
